name: Delete old ghrc images
on:
  workflow_dispatch:
  push:
    paths:
      - '.github/workflows/ghrc_cleanup/**'
      - '.github/workflows/ghrc_cleanup_v2.yaml'
  # schedule:
  #   - cron: '0 0 * * *' # every day at midnight
permissions:
  id-token: write
jobs:
  clean-ghcr:
    name: Delete old unused container images
    runs-on: ubuntu-latest
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Get token 🔑
      id: get-token
      uses: ./.github/workflows/get-auth-token/

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Get npm cache directory path
      id: npm-cache
      run: echo "::set-output name=dir::$(npm config get cache)"

    - name: Cache npm dependencies
      uses: actions/cache@v2
      with:
        path: ${{ steps.npm-cache.outputs.dir }}
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Install dependencies
      run: |
        npm install -g typescript
        npm install node-fetch @types/node

    - name: Compile TypeScript
      run: npx tsc '.github/workflows/ghrc_cleanup/cleanup.ts'

    - name: Make API request and process data
      run: node '.github/workflows/ghrc_cleanup/cleanup.js'

    - name: log-errors-to-slack 📄
      uses: act10ns/slack@v2
      with:
        status: ${{ job.status }}
        steps: ${{ toJson(steps) }}
      if: failure()
